package com.seamware.consentmanager.domain;

import io.micronaut.core.annotation.NonNull;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.data.annotation.Id;
import io.micronaut.data.annotation.MappedEntity;
import io.micronaut.data.annotation.MappedProperty;
import io.micronaut.data.annotation.TypeDef;
import io.micronaut.data.model.DataType;
import io.micronaut.serde.annotation.Serdeable;
import java.time.Instant;
import java.util.Map;
import java.util.UUID;

/**
 * Represents an audit log entry for a consent lifecycle event.
 *
 * <p>Each consent event records a state transition (e.g. granted, revoked, expired) for a specific
 * {@link Consent} record. Events are immutable once created and provide a complete audit trail of
 * all consent lifecycle changes.
 *
 * <p>This entity maps to the {@code consent_events} database table. Events are cascaded on delete
 * from their parent consent — when a consent record is deleted, all associated events are
 * automatically removed.
 *
 * <p>The primary key is a UUIDv7, generated by the application at construction time via {@link
 * UuidGenerator#uuidV7()}.
 */
@Serdeable
@MappedEntity("consent_events")
public class ConsentEvent {

    /** Default value for the event type when none is explicitly specified. */
    public static final String DEFAULT_EVENT_TYPE = "explicit";

    /** Unique surrogate primary key (UUIDv7, application-generated). */
    @Id private UUID id;

    /** The UUID of the {@link Consent} record this event belongs to. */
    @NonNull
    @MappedProperty("consent_id")
    private UUID consentId;

    /** The state transition recorded by this event (e.g. CONSENT_GIVEN, CONSENT_REVOKED). */
    @NonNull
    @MappedProperty("event_state")
    private ConsentEventState eventState;

    /**
     * The type of event trigger (e.g. "explicit" for user-initiated, "system" for automated).
     *
     * <p>Defaults to {@value #DEFAULT_EVENT_TYPE} when not explicitly specified.
     */
    @NonNull
    @MappedProperty("event_type")
    private String eventType;

    /**
     * Optional identifier of the actor who triggered this event (e.g. a user ID or system component
     * name).
     */
    @Nullable private String actor;

    /** Timestamp when this event occurred. */
    @NonNull
    @MappedProperty("occurred_at")
    private Instant occurredAt;

    /**
     * Optional JSONB-encoded additional details about the event.
     *
     * <p>May contain context-specific metadata such as reason codes, IP addresses, or change
     * descriptions. The structure varies by event type, so it is stored as a generic map.
     */
    @Nullable
    @TypeDef(type = DataType.JSON)
    private Map<String, Object> details;

    /**
     * Default no-argument constructor required by Micronaut Data.
     *
     * <p>Use the parameterized constructor for application-level entity creation.
     */
    public ConsentEvent() {}

    /**
     * Creates a new consent event with the required fields and optional metadata.
     *
     * <p>A UUIDv7 primary key is generated automatically via {@link UuidGenerator#uuidV7()}. The
     * event type defaults to {@value #DEFAULT_EVENT_TYPE}. The {@code occurredAt} timestamp is set
     * to the current time via {@link Instant#now()}.
     *
     * @param consentId the UUID of the consent record (must not be {@code null})
     * @param eventState the state transition being recorded (must not be {@code null})
     * @param actor the optional identifier of the triggering actor
     * @param details the optional JSONB event details
     */
    public ConsentEvent(
            @NonNull UUID consentId,
            @NonNull ConsentEventState eventState,
            @Nullable String actor,
            @Nullable Map<String, Object> details) {
        this.id = UuidGenerator.uuidV7();
        this.consentId = consentId;
        this.eventState = eventState;
        this.eventType = DEFAULT_EVENT_TYPE;
        this.actor = actor;
        this.occurredAt = Instant.now();
        this.details = details;
    }

    /**
     * Creates a new consent event with an explicit event type and timestamp.
     *
     * <p>A UUIDv7 primary key is generated automatically via {@link UuidGenerator#uuidV7()}.
     *
     * @param consentId the UUID of the consent record (must not be {@code null})
     * @param eventState the state transition being recorded (must not be {@code null})
     * @param eventType the type of event trigger (must not be {@code null})
     * @param actor the optional identifier of the triggering actor
     * @param occurredAt the timestamp when the event occurred (must not be {@code null})
     * @param details the optional JSONB event details
     */
    public ConsentEvent(
            @NonNull UUID consentId,
            @NonNull ConsentEventState eventState,
            @NonNull String eventType,
            @Nullable String actor,
            @NonNull Instant occurredAt,
            @Nullable Map<String, Object> details) {
        this.id = UuidGenerator.uuidV7();
        this.consentId = consentId;
        this.eventState = eventState;
        this.eventType = eventType;
        this.actor = actor;
        this.occurredAt = occurredAt;
        this.details = details;
    }

    /**
     * Returns the surrogate primary key.
     *
     * @return the UUID primary key, or {@code null} if not yet persisted
     */
    @Nullable
    public UUID getId() {
        return id;
    }

    /**
     * Sets the surrogate primary key.
     *
     * @param id the UUID primary key
     */
    public void setId(@Nullable UUID id) {
        this.id = id;
    }

    /**
     * Returns the UUID of the consent record this event belongs to.
     *
     * @return the consent UUID (never {@code null} once persisted)
     */
    @NonNull
    public UUID getConsentId() {
        return consentId;
    }

    /**
     * Sets the UUID of the consent record this event belongs to.
     *
     * @param consentId the consent UUID (must not be {@code null})
     */
    public void setConsentId(@NonNull UUID consentId) {
        this.consentId = consentId;
    }

    /**
     * Returns the state transition recorded by this event.
     *
     * @return the consent event state (never {@code null} once persisted)
     */
    @NonNull
    public ConsentEventState getEventState() {
        return eventState;
    }

    /**
     * Sets the state transition recorded by this event.
     *
     * @param eventState the consent event state (must not be {@code null})
     */
    public void setEventState(@NonNull ConsentEventState eventState) {
        this.eventState = eventState;
    }

    /**
     * Returns the type of event trigger.
     *
     * @return the event type (never {@code null}; defaults to {@value #DEFAULT_EVENT_TYPE})
     */
    @NonNull
    public String getEventType() {
        return eventType;
    }

    /**
     * Sets the type of event trigger.
     *
     * @param eventType the event type (must not be {@code null})
     */
    public void setEventType(@NonNull String eventType) {
        this.eventType = eventType;
    }

    /**
     * Returns the optional identifier of the actor who triggered this event.
     *
     * @return the actor identifier, or {@code null} if not recorded
     */
    @Nullable
    public String getActor() {
        return actor;
    }

    /**
     * Sets the identifier of the actor who triggered this event.
     *
     * @param actor the actor identifier, or {@code null} to clear
     */
    public void setActor(@Nullable String actor) {
        this.actor = actor;
    }

    /**
     * Returns the timestamp when this event occurred.
     *
     * @return the occurrence timestamp (never {@code null} once persisted)
     */
    @NonNull
    public Instant getOccurredAt() {
        return occurredAt;
    }

    /**
     * Sets the timestamp when this event occurred.
     *
     * @param occurredAt the occurrence timestamp (must not be {@code null})
     */
    public void setOccurredAt(@NonNull Instant occurredAt) {
        this.occurredAt = occurredAt;
    }

    /**
     * Returns the optional JSONB-encoded additional details about the event.
     *
     * @return the event details map, or {@code null} if not recorded
     */
    @Nullable
    public Map<String, Object> getDetails() {
        return details;
    }

    /**
     * Sets the JSONB-encoded additional details about the event.
     *
     * @param details the event details map, or {@code null} to clear
     */
    public void setDetails(@Nullable Map<String, Object> details) {
        this.details = details;
    }
}
