package com.seamware.consentmanager.domain;

import io.micronaut.core.annotation.NonNull;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.data.annotation.DateCreated;
import io.micronaut.data.annotation.DateUpdated;
import io.micronaut.data.annotation.Id;
import io.micronaut.data.annotation.MappedEntity;
import io.micronaut.data.annotation.MappedProperty;
import io.micronaut.data.annotation.TypeDef;
import io.micronaut.data.model.DataType;
import io.micronaut.serde.annotation.Serdeable;
import java.time.Instant;
import java.util.UUID;

/**
 * Represents a consent record in the consent management system.
 *
 * <p>A consent captures a user's decision regarding data processing under a specific privacy
 * notice. It links a {@link User} to a {@link PrivacyNotice} and records the consent status, the
 * provider and consumer {@link Participant participants}, and a frozen {@link ConsentSnapshot} of
 * the privacy notice terms at the time of consent.
 *
 * <p><strong>Status/consented invariant (bug 18.1 prevention):</strong> The {@code status} and
 * {@code consented} fields are always kept in sync. The {@code consented} flag is {@code true} only
 * when {@code status == GRANTED}; for all other statuses it is {@code false}. To enforce this
 * invariant, all status changes must go through the {@link #updateStatus(ConsentStatus)} method,
 * which atomically sets both fields. The public setter for {@code status} is intentionally omitted
 * to prevent callers from setting the status without updating the derived {@code consented} flag.
 *
 * <p>This entity maps to the {@code consents} database table. The primary key is a UUIDv7,
 * generated by the application at construction time via {@link UuidGenerator#uuidV7()}.
 */
@Serdeable
@MappedEntity("consents")
public class Consent {

    /** Unique surrogate primary key (UUIDv7, application-generated). */
    @Id private UUID id;

    /** The UUID of the {@link User} who granted (or is being asked for) consent. */
    @NonNull
    @MappedProperty("user_id")
    private UUID userId;

    /** The UUID of the {@link PrivacyNotice} that this consent is associated with. */
    @NonNull
    @MappedProperty("privacy_notice_id")
    private UUID privacyNoticeId;

    /** The UUID of the data provider {@link Participant}. */
    @NonNull
    @MappedProperty("provider_id")
    private UUID providerId;

    /** The UUID of the data consumer {@link Participant}. */
    @NonNull
    @MappedProperty("consumer_id")
    private UUID consumerId;

    /**
     * Optional UUID of a parent consent record, for consent chains or re-confirmations.
     *
     * <p>A self-referencing foreign key with {@code ON DELETE SET NULL}. The database enforces that
     * a consent cannot reference itself as its own parent via the {@code
     * chk_consents_no_self_parent} constraint.
     */
    @Nullable
    @MappedProperty("parent_consent_id")
    private UUID parentConsentId;

    /**
     * The lifecycle status of this consent.
     *
     * <p><strong>Do not set this field directly.</strong> Use {@link #updateStatus(ConsentStatus)}
     * to ensure the {@code consented} flag stays in sync. See class-level Javadoc for the
     * status/consented invariant.
     */
    @NonNull private ConsentStatus status;

    /**
     * Whether this consent is currently active (i.e. status is {@link ConsentStatus#GRANTED}).
     *
     * <p>This is a derived field that is always kept in sync with {@code status} via {@link
     * #updateStatus(ConsentStatus)}. It is {@code true} only when {@code status == GRANTED}.
     */
    private boolean consented;

    /** Optional URI of the contract associated with this consent. */
    @Nullable
    @MappedProperty("contract_uri")
    private String contractUri;

    /**
     * JSONB-encoded frozen copy of the privacy notice terms at the time consent was granted.
     *
     * <p>Preserves the exact terms the user agreed to, ensuring subsequent changes to the privacy
     * notice do not alter the historical record.
     */
    @NonNull
    @TypeDef(type = DataType.JSON)
    private ConsentSnapshot snapshot;

    /** Timestamp when this consent record was created; set automatically on insert. */
    @DateCreated
    @MappedProperty("created_at")
    private Instant createdAt;

    /** Timestamp when this consent record was last updated; set automatically on update. */
    @DateUpdated
    @MappedProperty("updated_at")
    private Instant updatedAt;

    /**
     * Default no-argument constructor required by Micronaut Data.
     *
     * <p>Use the static factory method {@link #withStatus(ConsentStatus, UUID, UUID, UUID, UUID,
     * UUID, String, ConsentSnapshot)} for application-level entity creation.
     */
    public Consent() {}

    /**
     * Creates a new consent record with the given status, atomically setting the {@code consented}
     * flag.
     *
     * <p>This is the designated factory method for creating {@code Consent} instances. It ensures
     * that the {@code status} and {@code consented} fields are always consistent: {@code consented}
     * is {@code true} only when {@code status == GRANTED}, and {@code false} for all other
     * statuses.
     *
     * <p><strong>Bug 18.1 prevention:</strong> By funneling all consent creation through this
     * factory method, callers cannot accidentally set {@code status} and {@code consented} to
     * inconsistent values.
     *
     * <p>A UUIDv7 primary key is generated automatically via {@link UuidGenerator#uuidV7()}.
     *
     * @param status the initial lifecycle status (must not be {@code null})
     * @param userId the UUID of the user (must not be {@code null})
     * @param privacyNoticeId the UUID of the privacy notice (must not be {@code null})
     * @param providerId the UUID of the data provider (must not be {@code null})
     * @param consumerId the UUID of the data consumer (must not be {@code null})
     * @param parentConsentId the optional UUID of a parent consent
     * @param contractUri the optional contract URI
     * @param snapshot the frozen privacy notice terms (must not be {@code null})
     * @return a new {@code Consent} instance with consistent status and consented fields
     */
    public static Consent withStatus(
            @NonNull ConsentStatus status,
            @NonNull UUID userId,
            @NonNull UUID privacyNoticeId,
            @NonNull UUID providerId,
            @NonNull UUID consumerId,
            @Nullable UUID parentConsentId,
            @Nullable String contractUri,
            @NonNull ConsentSnapshot snapshot) {
        var consent = new Consent();
        consent.id = UuidGenerator.uuidV7();
        consent.userId = userId;
        consent.privacyNoticeId = privacyNoticeId;
        consent.providerId = providerId;
        consent.consumerId = consumerId;
        consent.parentConsentId = parentConsentId;
        consent.status = status;
        consent.consented = status.isConsented();
        consent.contractUri = contractUri;
        consent.snapshot = snapshot;
        return consent;
    }

    /**
     * Updates the consent status and atomically recalculates the {@code consented} flag.
     *
     * <p>This is the <strong>only</strong> method that should be used to change the status of an
     * existing consent. It ensures the invariant that {@code consented == (status == GRANTED)} is
     * always maintained.
     *
     * <p><strong>Bug 18.1 prevention:</strong> Direct mutation of the {@code status} field is
     * intentionally not exposed via a public setter. All status transitions must go through this
     * method.
     *
     * @param newStatus the new lifecycle status (must not be {@code null})
     */
    public void updateStatus(@NonNull ConsentStatus newStatus) {
        this.status = newStatus;
        this.consented = newStatus.isConsented();
    }

    /**
     * Returns the surrogate primary key.
     *
     * @return the UUID primary key, or {@code null} if not yet persisted
     */
    @Nullable
    public UUID getId() {
        return id;
    }

    /**
     * Sets the surrogate primary key.
     *
     * @param id the UUID primary key
     */
    public void setId(@Nullable UUID id) {
        this.id = id;
    }

    /**
     * Returns the UUID of the user who granted (or is being asked for) consent.
     *
     * @return the user UUID (never {@code null} once persisted)
     */
    @NonNull
    public UUID getUserId() {
        return userId;
    }

    /**
     * Sets the UUID of the user.
     *
     * @param userId the user UUID (must not be {@code null})
     */
    public void setUserId(@NonNull UUID userId) {
        this.userId = userId;
    }

    /**
     * Returns the UUID of the privacy notice associated with this consent.
     *
     * @return the privacy notice UUID (never {@code null} once persisted)
     */
    @NonNull
    public UUID getPrivacyNoticeId() {
        return privacyNoticeId;
    }

    /**
     * Sets the UUID of the privacy notice.
     *
     * @param privacyNoticeId the privacy notice UUID (must not be {@code null})
     */
    public void setPrivacyNoticeId(@NonNull UUID privacyNoticeId) {
        this.privacyNoticeId = privacyNoticeId;
    }

    /**
     * Returns the UUID of the data provider participant.
     *
     * @return the provider UUID (never {@code null} once persisted)
     */
    @NonNull
    public UUID getProviderId() {
        return providerId;
    }

    /**
     * Sets the UUID of the data provider participant.
     *
     * @param providerId the provider UUID (must not be {@code null})
     */
    public void setProviderId(@NonNull UUID providerId) {
        this.providerId = providerId;
    }

    /**
     * Returns the UUID of the data consumer participant.
     *
     * @return the consumer UUID (never {@code null} once persisted)
     */
    @NonNull
    public UUID getConsumerId() {
        return consumerId;
    }

    /**
     * Sets the UUID of the data consumer participant.
     *
     * @param consumerId the consumer UUID (must not be {@code null})
     */
    public void setConsumerId(@NonNull UUID consumerId) {
        this.consumerId = consumerId;
    }

    /**
     * Returns the optional UUID of the parent consent record.
     *
     * @return the parent consent UUID, or {@code null} if this is a root consent
     */
    @Nullable
    public UUID getParentConsentId() {
        return parentConsentId;
    }

    /**
     * Sets the UUID of the parent consent record.
     *
     * @param parentConsentId the parent consent UUID, or {@code null} to clear
     */
    public void setParentConsentId(@Nullable UUID parentConsentId) {
        this.parentConsentId = parentConsentId;
    }

    /**
     * Returns the lifecycle status of this consent.
     *
     * @return the consent status (never {@code null} once persisted)
     */
    @NonNull
    public ConsentStatus getStatus() {
        return status;
    }

    /**
     * Returns whether this consent is currently active (granted).
     *
     * <p>This value is derived from the {@code status} field and is always {@code true} when {@code
     * status == GRANTED}, and {@code false} otherwise.
     *
     * @return {@code true} if the consent is granted, {@code false} otherwise
     */
    public boolean isConsented() {
        return consented;
    }

    /**
     * Sets the consented flag. This setter exists for Micronaut Data deserialization only.
     *
     * <p><strong>Application code should not call this method directly.</strong> Use {@link
     * #updateStatus(ConsentStatus)} or the {@link #withStatus(ConsentStatus, UUID, UUID, UUID,
     * UUID, UUID, String, ConsentSnapshot) withStatus} factory method instead to maintain the
     * status/consented invariant.
     *
     * @param consented the consented flag value
     */
    public void setConsented(boolean consented) {
        this.consented = consented;
    }

    /**
     * Sets the lifecycle status. This setter exists for Micronaut Data deserialization only.
     *
     * <p><strong>Application code should not call this method directly.</strong> Use {@link
     * #updateStatus(ConsentStatus)} or the {@link #withStatus(ConsentStatus, UUID, UUID, UUID,
     * UUID, UUID, String, ConsentSnapshot) withStatus} factory method instead to maintain the
     * status/consented invariant (bug 18.1 prevention).
     *
     * @param status the consent status
     */
    public void setStatus(@NonNull ConsentStatus status) {
        this.status = status;
    }

    /**
     * Returns the optional contract URI associated with this consent.
     *
     * @return the contract URI, or {@code null} if not set
     */
    @Nullable
    public String getContractUri() {
        return contractUri;
    }

    /**
     * Sets the contract URI.
     *
     * @param contractUri the contract URI, or {@code null} to clear
     */
    public void setContractUri(@Nullable String contractUri) {
        this.contractUri = contractUri;
    }

    /**
     * Returns the JSONB-encoded frozen copy of the privacy notice terms.
     *
     * @return the consent snapshot (never {@code null} once persisted)
     */
    @NonNull
    public ConsentSnapshot getSnapshot() {
        return snapshot;
    }

    /**
     * Sets the JSONB-encoded frozen copy of the privacy notice terms.
     *
     * @param snapshot the consent snapshot (must not be {@code null})
     */
    public void setSnapshot(@NonNull ConsentSnapshot snapshot) {
        this.snapshot = snapshot;
    }

    /**
     * Returns the timestamp when this consent record was created.
     *
     * @return the creation timestamp
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the creation timestamp. Normally managed by {@link DateCreated}.
     *
     * @param createdAt the creation timestamp
     */
    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Returns the timestamp when this consent record was last updated.
     *
     * @return the last-updated timestamp
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Sets the last-updated timestamp. Normally managed by {@link DateUpdated}.
     *
     * @param updatedAt the last-updated timestamp
     */
    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }
}
