package com.seamware.consentmanager.domain;

import io.micronaut.core.annotation.NonNull;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.data.annotation.DateCreated;
import io.micronaut.data.annotation.DateUpdated;
import io.micronaut.data.annotation.Id;
import io.micronaut.data.annotation.MappedEntity;
import io.micronaut.data.annotation.MappedProperty;
import io.micronaut.data.annotation.TypeDef;
import io.micronaut.data.model.DataType;
import io.micronaut.serde.annotation.Serdeable;
import java.time.Instant;
import java.util.Map;
import java.util.UUID;

/**
 * Represents a participant (data provider or consumer) in the consent management system.
 *
 * <p>A participant is an organization that either provides data (provider) or consumes data
 * (consumer) under the terms of a privacy notice. Each participant is uniquely identified by their
 * {@code identifier} and has a required legal name.
 *
 * <p>The {@code endpoints} field stores JSONB-encoded service endpoint information, and the
 * optional {@code legalPerson} field stores JSONB-encoded legal entity metadata (e.g. Gaia-X
 * self-description attributes). This entity maps to the {@code participants} database table.
 *
 * <p>The primary key is a UUIDv7, generated by the application at construction time via {@link
 * UuidGenerator#uuidV7()}. UUIDv7 embeds a millisecond timestamp, which improves B-tree insert
 * locality compared to fully random UUIDv4.
 */
@Serdeable
@MappedEntity("participants")
public class Participant {

    /** Unique surrogate primary key (UUIDv7, application-generated). */
    @Id private UUID id;

    /** External unique identifier for the participant. */
    @NonNull private String identifier;

    /** Official legal name of the participant organization. */
    @NonNull
    @MappedProperty("legal_name")
    private String legalName;

    /** Optional URI pointing to the participant's self-description document. */
    @Nullable
    @MappedProperty("self_description_uri")
    private String selfDescriptionUri;

    /** Optional contact email address for the participant. */
    @Nullable private String email;

    /**
     * JSONB-encoded service endpoint information for the participant.
     *
     * <p>Stored as a generic map since the endpoint structure is contract-dependent and may vary
     * between participants.
     */
    @NonNull
    @TypeDef(type = DataType.JSON)
    private Map<String, Object> endpoints;

    /**
     * Optional JSONB-encoded legal entity metadata for the participant.
     *
     * <p>May contain Gaia-X self-description attributes or other legal entity information. The
     * structure varies by deployment context, so it is stored as a generic map.
     */
    @Nullable
    @TypeDef(type = DataType.JSON)
    @MappedProperty("legal_person")
    private Map<String, Object> legalPerson;

    /** Timestamp when this participant record was created; set automatically on insert. */
    @DateCreated
    @MappedProperty("created_at")
    private Instant createdAt;

    /** Timestamp when this participant record was last updated; set automatically on update. */
    @DateUpdated
    @MappedProperty("updated_at")
    private Instant updatedAt;

    /**
     * When this participant deregistered, or {@code null} while it is still active.
     *
     * <p>Only set on a row deregistration had to retain because a consent or a privacy notice still
     * references it; a row nothing references is deleted outright.
     */
    @Nullable
    @MappedProperty("deregistered_at")
    private Instant deregisteredAt;

    /**
     * Default no-argument constructor required by Micronaut Data.
     *
     * <p>Use the parameterized constructor for application-level entity creation.
     */
    public Participant() {}

    /**
     * Creates a new participant with the required fields and optional metadata.
     *
     * <p>A UUIDv7 primary key is generated automatically via {@link UuidGenerator#uuidV7()}.
     *
     * @param identifier the external unique identifier (must not be {@code null})
     * @param legalName the official legal name (must not be {@code null})
     * @param selfDescriptionUri the optional URI to the self-description document
     * @param email the optional contact email address
     * @param endpoints the JSONB endpoint data (must not be {@code null})
     * @param legalPerson the optional JSONB legal entity metadata
     */
    public Participant(
            @NonNull String identifier,
            @NonNull String legalName,
            @Nullable String selfDescriptionUri,
            @Nullable String email,
            @NonNull Map<String, Object> endpoints,
            @Nullable Map<String, Object> legalPerson) {
        this.id = UuidGenerator.uuidV7();
        this.identifier = identifier;
        this.legalName = legalName;
        this.selfDescriptionUri = selfDescriptionUri;
        this.email = email;
        this.endpoints = endpoints;
        this.legalPerson = legalPerson;
    }

    /**
     * Returns the surrogate primary key.
     *
     * @return the UUID primary key, or {@code null} if not yet persisted
     */
    @Nullable
    public UUID getId() {
        return id;
    }

    /**
     * Sets the surrogate primary key.
     *
     * @param id the UUID primary key
     */
    public void setId(@Nullable UUID id) {
        this.id = id;
    }

    /**
     * Returns the external unique identifier for the participant.
     *
     * @return the identifier string (never {@code null} once persisted)
     */
    @NonNull
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the external unique identifier for the participant.
     *
     * @param identifier the identifier string (must not be {@code null})
     */
    public void setIdentifier(@NonNull String identifier) {
        this.identifier = identifier;
    }

    /**
     * Returns the official legal name of the participant organization.
     *
     * @return the legal name (never {@code null} once persisted)
     */
    @NonNull
    public String getLegalName() {
        return legalName;
    }

    /**
     * Sets the official legal name of the participant organization.
     *
     * @param legalName the legal name (must not be {@code null})
     */
    public void setLegalName(@NonNull String legalName) {
        this.legalName = legalName;
    }

    /**
     * Returns the optional URI to the participant's self-description document.
     *
     * @return the self-description URI, or {@code null} if not set
     */
    @Nullable
    public String getSelfDescriptionUri() {
        return selfDescriptionUri;
    }

    /**
     * Sets the URI to the participant's self-description document.
     *
     * @param selfDescriptionUri the self-description URI, or {@code null} to clear
     */
    public void setSelfDescriptionUri(@Nullable String selfDescriptionUri) {
        this.selfDescriptionUri = selfDescriptionUri;
    }

    /**
     * Returns the optional contact email address for the participant.
     *
     * @return the email address, or {@code null} if not set
     */
    @Nullable
    public String getEmail() {
        return email;
    }

    /**
     * Sets the contact email address for the participant.
     *
     * @param email the email address, or {@code null} to clear
     */
    public void setEmail(@Nullable String email) {
        this.email = email;
    }

    /**
     * Returns the JSONB-encoded service endpoint information.
     *
     * @return the endpoints map (never {@code null} once persisted)
     */
    @NonNull
    public Map<String, Object> getEndpoints() {
        return endpoints;
    }

    /**
     * Sets the JSONB-encoded service endpoint information.
     *
     * @param endpoints the endpoints map (must not be {@code null})
     */
    public void setEndpoints(@NonNull Map<String, Object> endpoints) {
        this.endpoints = endpoints;
    }

    /**
     * Returns the optional JSONB-encoded legal entity metadata.
     *
     * @return the legal person map, or {@code null} if not set
     */
    @Nullable
    public Map<String, Object> getLegalPerson() {
        return legalPerson;
    }

    /**
     * Sets the JSONB-encoded legal entity metadata.
     *
     * @param legalPerson the legal person map, or {@code null} to clear
     */
    public void setLegalPerson(@Nullable Map<String, Object> legalPerson) {
        this.legalPerson = legalPerson;
    }

    /**
     * Returns the timestamp when this participant record was created.
     *
     * @return the creation timestamp
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the creation timestamp. Normally managed by {@link DateCreated}.
     *
     * @param createdAt the creation timestamp
     */
    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Returns the timestamp when this participant record was last updated.
     *
     * @return the last-updated timestamp
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Sets the last-updated timestamp. Normally managed by {@link DateUpdated}.
     *
     * @param updatedAt the last-updated timestamp
     */
    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Returns when this participant deregistered.
     *
     * @return the deregistration timestamp, or {@code null} while the participant is active
     */
    @Nullable
    public Instant getDeregisteredAt() {
        return deregisteredAt;
    }

    /**
     * Sets the deregistration timestamp.
     *
     * @param deregisteredAt when the participant deregistered, or {@code null} to reactivate it
     */
    public void setDeregisteredAt(@Nullable Instant deregisteredAt) {
        this.deregisteredAt = deregisteredAt;
    }
}
