package com.seamware.consentmanager.domain;

import io.micronaut.core.annotation.NonNull;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.data.annotation.DateCreated;
import io.micronaut.data.annotation.DateUpdated;
import io.micronaut.data.annotation.Id;
import io.micronaut.data.annotation.MappedEntity;
import io.micronaut.data.annotation.MappedProperty;
import io.micronaut.data.annotation.TypeDef;
import io.micronaut.data.model.DataType;
import io.micronaut.serde.annotation.Serdeable;
import java.time.Instant;
import java.util.UUID;

/**
 * Represents a privacy notice in the consent management system.
 *
 * <p>A privacy notice defines the terms under which personal data is processed between a data
 * provider and an optional data consumer. It references a contract URI and contains a JSONB {@link
 * PrivacyNoticePayload} with the contract-derived details (purposes, data categories, recipient
 * information, etc.).
 *
 * <p>Privacy notices can be archived by setting {@code archivedAt} to a non-null timestamp. A
 * partial unique index on {@code (contract_uri, provider_id) WHERE archived_at IS NULL} ensures
 * that only one active (non-archived) privacy notice exists per contract/provider combination.
 *
 * <p>This entity maps to the {@code privacy_notices} database table. The primary key is a UUIDv7,
 * generated by the application at construction time via {@link UuidGenerator#uuidV7()}.
 */
@Serdeable
@MappedEntity("privacy_notices")
public class PrivacyNotice {

    /** Unique surrogate primary key (UUIDv7, application-generated). */
    @Id private UUID id;

    /** The URI identifying the contract that this privacy notice is derived from. */
    @NonNull
    @MappedProperty("contract_uri")
    private String contractUri;

    /** Optional human-readable title for the privacy notice. */
    @Nullable private String title;

    /** The UUID of the data provider {@link Participant} associated with this privacy notice. */
    @NonNull
    @MappedProperty("provider_id")
    private UUID providerId;

    /**
     * The optional UUID of the data consumer {@link Participant} associated with this privacy
     * notice.
     */
    @Nullable
    @MappedProperty("consumer_id")
    private UUID consumerId;

    /**
     * JSONB-encoded payload containing the contract-derived privacy notice content.
     *
     * <p>Includes purposes, data categories, recipients, controller details, retention period, PII
     * principal rights, international transfers, and withdrawal method.
     */
    @NonNull
    @TypeDef(type = DataType.JSON)
    private PrivacyNoticePayload payload;

    /**
     * Timestamp when this privacy notice was archived, or {@code null} if it is still active.
     *
     * <p>Archiving a privacy notice frees the {@code (contract_uri, provider_id)} slot so that a
     * new active notice can be created for the same contract/provider combination.
     */
    @Nullable
    @MappedProperty("archived_at")
    private Instant archivedAt;

    /** Timestamp when this privacy notice record was created; set automatically on insert. */
    @DateCreated
    @MappedProperty("created_at")
    private Instant createdAt;

    /** Timestamp when this privacy notice record was last updated; set automatically on update. */
    @DateUpdated
    @MappedProperty("updated_at")
    private Instant updatedAt;

    /**
     * Default no-argument constructor required by Micronaut Data.
     *
     * <p>Use the parameterized constructor for application-level entity creation.
     */
    public PrivacyNotice() {}

    /**
     * Creates a new privacy notice with the required fields and optional metadata.
     *
     * <p>A UUIDv7 primary key is generated automatically via {@link UuidGenerator#uuidV7()}.
     *
     * @param contractUri the URI identifying the contract (must not be {@code null})
     * @param title the optional human-readable title
     * @param providerId the UUID of the data provider participant (must not be {@code null})
     * @param consumerId the optional UUID of the data consumer participant
     * @param payload the JSONB privacy notice payload (must not be {@code null})
     */
    public PrivacyNotice(
            @NonNull String contractUri,
            @Nullable String title,
            @NonNull UUID providerId,
            @Nullable UUID consumerId,
            @NonNull PrivacyNoticePayload payload) {
        this.id = UuidGenerator.uuidV7();
        this.contractUri = contractUri;
        this.title = title;
        this.providerId = providerId;
        this.consumerId = consumerId;
        this.payload = payload;
    }

    /**
     * Returns the surrogate primary key.
     *
     * @return the UUID primary key, or {@code null} if not yet persisted
     */
    @Nullable
    public UUID getId() {
        return id;
    }

    /**
     * Sets the surrogate primary key.
     *
     * @param id the UUID primary key
     */
    public void setId(@Nullable UUID id) {
        this.id = id;
    }

    /**
     * Returns the contract URI that this privacy notice is derived from.
     *
     * @return the contract URI (never {@code null} once persisted)
     */
    @NonNull
    public String getContractUri() {
        return contractUri;
    }

    /**
     * Sets the contract URI.
     *
     * @param contractUri the contract URI (must not be {@code null})
     */
    public void setContractUri(@NonNull String contractUri) {
        this.contractUri = contractUri;
    }

    /**
     * Returns the optional human-readable title.
     *
     * @return the title, or {@code null} if not set
     */
    @Nullable
    public String getTitle() {
        return title;
    }

    /**
     * Sets the human-readable title.
     *
     * @param title the title, or {@code null} to clear
     */
    public void setTitle(@Nullable String title) {
        this.title = title;
    }

    /**
     * Returns the UUID of the data provider participant.
     *
     * @return the provider participant UUID (never {@code null} once persisted)
     */
    @NonNull
    public UUID getProviderId() {
        return providerId;
    }

    /**
     * Sets the UUID of the data provider participant.
     *
     * @param providerId the provider participant UUID (must not be {@code null})
     */
    public void setProviderId(@NonNull UUID providerId) {
        this.providerId = providerId;
    }

    /**
     * Returns the optional UUID of the data consumer participant.
     *
     * @return the consumer participant UUID, or {@code null} if not set
     */
    @Nullable
    public UUID getConsumerId() {
        return consumerId;
    }

    /**
     * Sets the UUID of the data consumer participant.
     *
     * @param consumerId the consumer participant UUID, or {@code null} to clear
     */
    public void setConsumerId(@Nullable UUID consumerId) {
        this.consumerId = consumerId;
    }

    /**
     * Returns the JSONB-encoded privacy notice payload.
     *
     * @return the privacy notice payload (never {@code null} once persisted)
     */
    @NonNull
    public PrivacyNoticePayload getPayload() {
        return payload;
    }

    /**
     * Sets the JSONB-encoded privacy notice payload.
     *
     * @param payload the privacy notice payload (must not be {@code null})
     */
    public void setPayload(@NonNull PrivacyNoticePayload payload) {
        this.payload = payload;
    }

    /**
     * Returns the timestamp when this privacy notice was archived.
     *
     * @return the archive timestamp, or {@code null} if the notice is still active
     */
    @Nullable
    public Instant getArchivedAt() {
        return archivedAt;
    }

    /**
     * Sets the archive timestamp for this privacy notice.
     *
     * @param archivedAt the archive timestamp, or {@code null} to mark as active
     */
    public void setArchivedAt(@Nullable Instant archivedAt) {
        this.archivedAt = archivedAt;
    }

    /**
     * Returns the timestamp when this privacy notice record was created.
     *
     * @return the creation timestamp
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the creation timestamp. Normally managed by {@link DateCreated}.
     *
     * @param createdAt the creation timestamp
     */
    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Returns the timestamp when this privacy notice record was last updated.
     *
     * @return the last-updated timestamp
     */
    public Instant getUpdatedAt() {
        return updatedAt;
    }

    /**
     * Sets the last-updated timestamp. Normally managed by {@link DateUpdated}.
     *
     * @param updatedAt the last-updated timestamp
     */
    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }
}
